export interface BdBanDocProfile {
  id?: string;
  bsThuVienTen?: string;
  bdNhomTen?: string;
  soThe?: string;
  hoTen?: string;
  gioiTinh?: string;
  ngaySinh?: string;
  email?: string;
  dienThoai?: string;
  anhDaiDien?: string | null;
  ngayBatDau?: string;
  ngayKetThuc?: string;
  giaHanThe?: number;
  ngayKhoaTheTu?: string;
  ngayKhoaTheDen?: string;
  bdDmQuocGiaId?: string;
  bdDmTinhThanhId?: string;
  diaChi?: string;
  nguoiLienHe?: string;
  cccdSo?: string;
  cccdNgayCap?: string;
  cccdNoiCap?: string;
  tvccLaThe?: string;
  tvccLaTheQuy?: string;
  tvccLePhiTienCuoc?: number | null;
  tvccLePhiLamThe?: number | null;
  tvccLePhiMienGiam?: string;
  bdDmDanTocTen?: string;
  bdDmNgheNghiepTen?: string;
  bdDmTrinhDoVanHoaTen?: string;
  bdDmThanhPhanXaHoiTen?: string;
  bdDmTruongHocTen?: string;
  bdDmLyDoKhoaTheTen?: string;
  bdDmLoaiTheTen?: string;
  bdDmQuocGiaTen?: string;
  bdDmTinhThanhTen?: string;
  mhDmKhoaHocTen?: string;
  mhDmHeDaoTaoTen?: string;
  mhDmNganhHocTen?: string;
  mhDmNganhHocChuyenNganhTen?: string;
  mhDmLopHocTen?: string;
  soTien?: number;
}